spring:
  application:
    name: sync-prcs
  datasource:
    source-db:
      url: jdbc:h2:mem:source;DB_CLOSE_DELAY=-1
      driver-class-name: org.h2.Driver
      username: sa
      hikari:
        connection-timeout: 30000
        idle-timeout: 600000
        max-lifetime: 1800000
    dest-db:
      url: jdbc:h2:mem:dest;DB_CLOSE_DELAY=-1
      driver-class-name: org.h2.Driver
      username: sa
      hikari:
        connection-timeout: 30000
        idle-timeout: 600000
        max-lifetime: 1800000
  jpa:
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update


