CREATE TABLE IF NOT EXISTS TRANSFER(
    TRANSFER_ID INTEGER,
    ACCOUNT_ID_ORIGIN VARCHAR(20),
    ACCOUNT_ID_DEST VARCHAR(20),
    AMOUNT DECIMAL,
    TRANSFER_DT TIMESTAMP
);

INSERT INTO TRANSFER VALUES (1, '00121', '11121', 8.99, CURRENT_TIMESTAMP);
COMMIT;
